---
title: "Midterm Project"
author: "Razan Ahsan Rifandi"
date: "2025-03-16"
output: html_document
---

```{r}
library(httr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(kableExtra)
library(GGally)
```

# Data Collection and Wrangling

```{r}
anime_data <- list()

for (y in 2015:2024) {
  for (s in c('Winter', 'Spring', 'Summer', 'Fall')) {
    page <- 1
    while (TRUE) {
      response <- GET(
        paste0("https://api.jikan.moe/v4/seasons/", y, "/", tolower(s), "?page=", page)
      )
      
      if (status_code(response) == 200) {
        data <- fromJSON(content(response, "text"))
        
        anime_list <- data$data |>
          mutate(title_english = coalesce(title_english, title), year = coalesce(year, y)) |>
          select(mal_id, title_english, type, source, airing, year, rating, 
            score, members, favorites,
            # producers, licensors,
            studios, genres) |>
          mutate(
            # producers = sapply(producers, function(x) paste(x$name, collapse = ", ")),
            # licensors = sapply(licensors, function(x) paste(x$name, collapse = ", ")),
            studios = sapply(studios, function(x) paste(x$name, collapse = ", ")),
            genres = sapply(genres, function(x) paste(x$name, collapse = ", "))
          )
        
        anime_data <- append(anime_data, list(anime_list))
        
        total_pages <- ceiling(data$pagination$items$total / data$pagination$items$per_page)
        
        if (page >= total_pages) {
          break
        } else {
          page <- page + 1
        }
      } else {
        message(paste("Failed to fetch data for", year, season, "on page", page, ":", status_code(response)))
        print(paste0("https://api.jikan.moe/v4/seasons/", year, "/", season))
      }
      Sys.sleep(1)
    }
  }
}

anime_data <- do.call(rbind, anime_data)
```

```{r}
# Optional: Save the raw extracted data in a csv file
# write.csv(anime_data, file = "mal_anime_2015_2024_raw.csv", row.names = FALSE)
```

```{r}
# Optional: read the raw extracted data from our .csv file
# anime_data <- read.csv("mal_anime_2015_2024_raw.csv")
```

```{r}
# Check for duplicated entries
duplicates <- anime_data[duplicated(anime_data$mal_id), ]
print(duplicates)
```

# Data Cleaning

```{r}
# 1. Remove duplicates and remove mal_id column
anime_data <- anime_data |>
  distinct(mal_id, .keep_all = TRUE) |>
  select(-c(mal_id))
```

```{r}
# 2. Filter the entries to what we consider an "anime" in the research question,
#    which are animated shows with theatrical or television broadcast

# Check types of entries
unique(anime_data$type)

# Filter based on the values of type
anime_data <- anime_data |>
  filter(type %in% c("TV", "Movie"))
```

```{r}
# 3. Remove currently airing anime
anime_data <- anime_data |>
  filter(!airing) |>
  select(-c(airing))
```

```{r}
# 4. Data reformating: NA values for studios, genres, and source;
#    Mutate year to integer
anime_data <- anime_data |>
  mutate(
    studios = na_if(studios, ""),
    genres = na_if(genres, ""),
    source = na_if(source, "Unknown"),
    year = as.integer(year)
  )

# Check NA values
colSums(is.na(anime_data))
```

```{r}
# 4. Remove NA Values
anime_data <- anime_data |>
  filter(!is.na(score)) |>
  filter(!is.na(rating)) |>
  filter(!is.na(studios)) |>
  filter(!is.na(genres))
```

```{r}
# Final dimension of anime_data
dim(anime_data)
```

```{r}
# Save the cleaned data to a .csv file
write.csv(anime_data, file = "mal_anime_2015_2024.csv", row.names = FALSE)
```

```{r}
# Optional: read the cleaned data from our .csv file
# anime_data <- read.csv(file = "mal_anime_2015_2024.csv")
```

# Exploratory Data Analysis (EDA)

```{r}
summary(anime_data)
```

```{r}
anime_data |>
  group_by(type) |>
  summarise(count = n(), .groups = 'drop') |>
  kable(caption = "Count of Anime Types (TV and Movie)", col.names = c("Type", "Count")) |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
anime_data |>
  group_by(source) |>
  summarise(count = n(), .groups = 'drop') |>
  arrange(desc(count)) |>
  kable(caption = "Count of Anime Source Material Type", col.names = c("Type", "Count")) |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
anime_data |>
  group_by(rating) |>
  summarise(count = n(), .groups = 'drop') |>
  arrange(desc(count)) |>
  kable(caption = "Count of Anime Rating", col.names = c("Type", "Count")) |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
anime_data |>
  group_by(year) |>
  summarise(count = n(), .groups = 'drop') |>
  ggplot(aes(x = factor(year), y = count)) +  
    geom_bar(stat = "identity", fill = "steelblue") +     
    labs(title = "Number of Anime by Year",             
         x = "Year",                                    
         y = "Count") +                                  
    theme_minimal()
```

```{r}
# cont vars: scores, members, favorites
anime_data |>
  summarise(
    score_mean = mean(score, na.rm = TRUE),
    score_median = median(score, na.rm = TRUE),
    score_min = min(score, na.rm = TRUE),
    score_max = max(score, na.rm = TRUE),
    score_sd = sd(score, na.rm = TRUE),

    members_mean = mean(members, na.rm = TRUE),
    members_median = median(members, na.rm = TRUE),
    members_min = min(members, na.rm = TRUE),
    members_max = max(members, na.rm = TRUE),
    members_sd = sd(members, na.rm = TRUE),

    favorites_mean = mean(favorites, na.rm = TRUE),
    favorites_median = median(favorites, na.rm = TRUE),
    favorites_min = min(favorites, na.rm = TRUE),
    favorites_max = max(favorites, na.rm = TRUE),
    favorites_sd = sd(favorites, na.rm = TRUE)
  ) |>
  pivot_longer(everything(), names_to = "metric", values_to = "value") |>
  separate(metric, into = c("variable", "statistic"), sep = "_") |>
  pivot_wider(names_from = statistic, values_from = value) |>
  kable(caption = "Summary Statistics of Score, Members, and Favorites") |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
anime_data |>
  ggplot(aes(x = score)) +
  geom_histogram(binwidth = 0.5, fill = "steelblue", color = "black") +
  labs(title = "Distribution of Anime Scores",
       x = "Score",
       y = "Count") +
  theme_minimal()
```

```{r}
anime_data |>
  ggplot(aes(x = members)) +
  geom_histogram(fill = "steelblue", color = "black") +
  labs(title = "Distribution of Anime Members",
       x = "Members",
       y = "Count") +
  theme_minimal()
```

```{r}
anime_data |>
  ggplot(aes(x = favorites)) +
  geom_histogram(fill = "steelblue", color = "black") +
  labs(title = "Distribution of Anime Favorites",
       x = "Favorites",
       y = "Count") +
  theme_minimal()
```

```{r}
anime_data |>
  ggplot(aes(x = log(members + 1))) +
  geom_histogram(fill = "steelblue", color = "black") +
  labs(title = "Distribution of Anime Members (logged)",
       x = "Members",
       y = "Count") +
  theme_minimal()
```

```{r}
anime_data |>
  ggplot(aes(x = log(favorites + 1))) +
  geom_histogram(fill = "steelblue", color = "black") +
  labs(title = "Distribution of Anime Favorites (logged)",
       x = "Favorites",
       y = "Count") +
  theme_minimal()
```

```{r}
# scores vs type
anime_data |>
  ggplot(aes(x = type, y = score, fill = type)) +
  geom_boxplot() +
  labs(title = "Box Plot of Score by Type",
       x = "Type",
       y = "Score") +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
# Box plot for score vs source material
anime_data |>
  ggplot(aes(x = source, y = score, fill = source)) +
  geom_boxplot() +
  labs(title = "Box Plot of Score by Source",
       x = "Source",
       y = "Score") +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# score vs age rating
anime_data |>
  ggplot(aes(x = rating, y = score, fill = rating)) +
  geom_boxplot() +
  labs(title = "Box Plot of Score by Age Rating",
       x = "Rating",
       y = "Score") +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# scores vs year
anime_data |>
  mutate(year = factor(year)) |>
  ggplot(aes(x = year, y = score, fill = year)) +
  geom_boxplot() +
  labs(title = "Box Plot of Score by Year",
       x = "Source",
       y = "Score") +
  theme_minimal() +
  theme(legend.position = "none")
```

```{r}
# summary statistics of scores vs studio
anime_data |>
  separate_rows(studios, sep = ", ") |>
  group_by(studios) |>
  summarise(
    count = n(), .groups = 'drop',
    score_mean = mean(score, na.rm = TRUE),
    score_median = median(score, na.rm = TRUE),
    score_min = min(score, na.rm = TRUE),
    score_max = max(score, na.rm = TRUE),
    score_sd = sd(score, na.rm = TRUE)
  ) |>
  arrange(desc(score_mean)) |>
  kable(caption = "Summary statistics of Scores grouped by Each Studio") |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
# summary statistics of scores vs each genre
anime_data |>
  separate_rows(genres, sep = ", ") |>
  group_by(genres) |>
  summarise(
    count = n(), .groups = 'drop',
    score_mean = mean(score, na.rm = TRUE),
    score_median = median(score, na.rm = TRUE),
    score_min = min(score, na.rm = TRUE),
    score_max = max(score, na.rm = TRUE),
    score_sd = sd(score, na.rm = TRUE)
  ) |>
  arrange(desc(score_mean)) |>
  kable(caption = "Summary statistics of Score grouped by Each Genre") |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r}
# Pair scatterplot of continous variables
anime_data |>
  mutate(log_members = log(members + 1),
    log_favorites = log(favorites + 1)) |>
  ggpairs(columns = c("score", "log_members", "log_favorites"),
    title = "Pair Scatterplot of Score, Log(Members), and Log(Favorites)",
    upper = list(continuous = wrap("cor", size = 5)),
    lower = list(continuous = wrap("smooth", alpha = 0.5, color = "steelblue"))) +
  theme_minimal()
```